name: Finally Generate Docs

on:
  push:
    branches:
      - master
jobs:
  generate-docs:
    runs-on: windows-latest
    name: Finally Generate Docs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core 3.1
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.300"
      - name: Generate Documentation
        uses: FuLagann/csharp-docs-generator@v1.0
        with:
          build-tasks: dotnet build
          cleanup-tasks: dotnet clean
          binaries: D:\УЧЕБА\Готовые к сдаче\3 курс\Моделирование систем\СДАНЫ\SetkaWF\SetkaWF\bin\Debug\netcoreapp3.1\SetkaWF.deps.json
          output-path: docs/api
          user-email: csharp.doc.gen@gmail.com
          user-name: C# Document Generator
