name: Build and Generate Docs

on:
  push:
    branches:
      - dev #чтобы action выполнялся, нужно поменять на master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Framework
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --configuration Release

      - name: Generate Documentation 1
        run: dotnet build /t:Clean,Build /p:Configuration=Debug  /p:DocumentationFile=Output.chm /p:CleanIntermediates=True /p:Platform="Any CPU" /p:ProjectReferencePaths=References /p:HelpFormat=HtmlHelp1 /p:HtmlHelpName="My App Help" /p:HtmlHelp2Enabled=false /p:KeepLogFile=True /p:Logging=Verbose /p:PresentationStyle=VS2015 /p:SandcastlePath="C:\Program Files (x86)\Sandcastle\"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Docs
          path: .\outputs\test1.zip
          
      - name: Generate Documentation 2
        run: dotnet build /t:Clean,Build /p:Configuration=Debug /p:DocumentationFile=./outputs/Output.chm /p:CleanIntermediates=True /p:Platform="Any CPU" /p:ProjectReferencePaths=References /p:HelpFormat=HtmlHelp1 /p:HtmlHelpName="My App Help" /p:HtmlHelp2Enabled=false /p:KeepLogFile=True /p:Logging=Verbose /p:PresentationStyle=VS2015 /p:SandcastlePath="C:\Program Files (x86)\Sandcastle\"

      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: Docs ${{ github.run_number }}
          path: .\outputs\test1.zip

          
          
